# Generated by Django 6.1 on 2026-09-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('BACKLOG', 'Backlog'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], max_length=20, null=True),
        ),
    ]
